source("http://www.bioconductor.org/biocLite.R")
biocLite(c(
"biomaRt",
"clusterProfiler",
"ComplexHeatmap",
"DESeq2",
"fgsea",
"GenomicAlignments",
"GenomicFeatures",
"GenomicRanges",
"GEOquery",
"ggbio",
"Glimma",
"GO.db",
"goseq",
"limma",
"pathview",
"rtracklayer"))

install.packages(c(
"ggfortify",
"gplots",
"RColorBrewer",
"tidyverse"),
repos="https://cran.ma.imperial.ac.uk/")
